image: $CI_REGISTRY/msl/tools/satplot:0.3
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint:
  script:
    - ruff check

test:
  script:
    - pytest

type:
  script:
    - mypy satplot