name: Bug Report
description: Create a new bug report.
title: '[Bug]: <title>'
labels: [type:bug]
body:

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: 'Please [search :mag: the issues](https://github.com/rzmearns/OrbViz/issues) (open & closed) to check if this bug has already been reported.'
      options:
      - label: I have searched the existing issues
        required: true

  - type: input
    attributes:
      label: OrbViz Version
      description: What OrbViz version are you using?
      placeholder: Output of `OrbViz.__version__`
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Is this issue reproducible using the latest OrbViz version?
      description: |
        You can check the latest OrbViz version number in the help>>about menu of the application
      options:
      - label: I confirm the issue is still reproducible with the latest version

  - type: textarea
    attributes:
      label: Current Behaviour
      description: Describe the problem you are experiencing. Screenshots are welcome. Please enclose copied code in ```.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: Describe what you expect to happen instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Details
      description: |
        Please provide additional information about your environment; python version, etc.

        :warning: _Remember to redact or remove any sensitive information!_
      value: |
          - Python version
          - Are you running python in a virtual environment
          - Are you using the default OrbViz configuration or using a OrbViz_CONFIG_DIR:
          - Are you using spacetrack credentials, or faling back to celestrak
          - Last OrbViz version(s) which did _not_ exhibit the problem:

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide [the smallest, complete code snippet](https://stackoverflow.com/help/minimal-reproducible-example) that OrbViz's maintainers can run to reproduce the issue. An easy way to get started is to copy the examples in [README](https://github.com/rzmearns/OrbViz/blob/main/README.md) and modify it accordingly. Failing this, any sort of reproduction steps are better than nothing!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Further Information
      description: If needed, please provide additional information about your issue (attachments, links, references, etc.).

  - type: markdown
    attributes:
      value: ':stop_sign: _Make sure you are reporting a problem with OrbViz. For general questions, please ask a [question](https://github.com/rzmearns/OrbViz/issues)_'
